### ISSUE TITLE
Release Plan: 1.7.0

### ISSUE THREAD

**Issue by davemoore-** [zentity-io/zentity#60]
# Release Plan: 1.7.0

## Changes

- [x] Feature: Allow attributes to be represented as nested fields. (Issue: #77) (PR: #80)
- [x] Breaking Change: Enforce naming requirements for entity types (Issue: #58) (PR: #63)
- [x] Breaking Change: Enforce naming requirements for attributes, resolvers, and matchers (Issue: #73) (PR: #75)
- [x] Minor: Allow more lenient validation of empty objects in Models API (Issue: #72) (PR: #74)
- [x] Minor: Allow integers to be given as inputs to float fields (Issue: #59)

## Release

- [X] Create branch `1.7.0` from `main` branch
- [X] Update `zentity.version` in pom.xml and version numbers in README.md
- [X] Tag as `zentity-1.7.0` and push to build and deploy its release artifacts
- [x] Verify successful deployment

## Post-release

- [x] Update zentity.io home
- [x] Update zentity.io releases
- [x] Update zentity.io documentation

**Comment by davemoore-** [comment]
I moved the bulk operations features to 1.8.0 (#78), because this release is required for zentity-ui and is likely to be completed sooner.
