### ISSUE TITLE
Release Plan: 1.6.2

### ISSUE THREAD

**Issue by davemoore-** [zentity-io/zentity#65]
# Release Plan: 1.6.2

## Changes

- [x] Bug fix: Blocking calls leads to cluster instability (Issue: #56) (PR: #67)

## Blockers

- [x] Enable assertions in integration tests (Issue: #64) (PR: #67)
- [x] Use multi-node clusters for integration tests (Issue: #68) (PR: #70)
- [x] Migrate from Travis CI to GitHub Actions (Issue: #54) (PR: #69)

## Post-release

- [x] Update zentity.io releases

**Comment by davemoore-** [comment]
Released
