### ISSUE TITLE
Use a multi-node cluster in production mode for integration tests

### ISSUE THREAD

**Issue by davemoore-** [zentity-io/zentity#68]
Issues like #56 have shown that a multi-node cluster in production mode would be better to run integration tests on than a single-node cluster in development mode. The plugin should be tested in an environment that more closely represents the desired state in which it will operate.

- [x] Migrate to GitHub Actions (Issue: #54) (PR: #69)
- [x] Modify GitHub Actions workflows to install docker-compose (if needed)
- [x] Create docker-compose file with a multi-node production-mode cluster for use in testing (PR: #70)
- [x] ~Modify ./src/test/ant/integration-tests.xml to run test cluster with docker-compose~ Retire Ant (PR: #70)

**Comment by austince** [comment]
I think this could also be implemented with [testcontainers](https://www.testcontainers.org/) which, if we're already introducing the docker dependency for int tests, might be a more integrated and repeatable testing experience. I think that could remove the Ant dependency as well, which might modernize the test stack a bit.

**Comment by davemoore-** [comment]
++ on testcontainers, I tried it out this morning and eventually got it to behave the way I was hoping. Available at PR #70.

**Comment by davemoore-** [comment]
Merged into master
